version: '3.8'

services:
  se-torchapi-linux:
    build: .
    image: spaceengineers:torchapi
    container_name: torchapi
    restart: unless-stopped
    volumes:
      - ./torch-server:/app/torch-server
    ports:
     - "27016:27016/udp"
     - "5900:5900"
    environment: 
      - WINEDEBUG=-all
      - INSTANCE_NAME=TORCHAPI
